### ISSUE TITLE
Sólo desempata con base en el último achievment?

### ISSUE THREAD

**Issue by nihilia10** [heavy-duty/calculate-leaderboard#1]
Estaba revisando el código y veo que utilizan un parámetro llamado LatestDate. toman el mayor de estos valores y lo rodenan ascendentemente.
Pero qué pasa en el siguiente caso:
En el achivment X:

- Juanita, {puntos: 1,  fecha: 7:00}
- Carlos, {puntos: 1, fecha: 7:05}

En este caso Juanita queda de primeras porque contestó bien, está perfecto. Pero si hay un nuevo achivment X+1:

- Juanita, {puntos: 1,  fecha: 9:01}
- Carlos, {puntos: 1, fecha: 9:00}

Entiendo que en este caso, Carlos quedaría de primero porque su "última fecha" es antes que la de Juanita, pero en el primer achievment Juanita le llevó 5 minutos de diferencia, en el segundo solo perdió por 1 minuto. entonces creería que lo más "justo" es que igual Juanita quede de primeras.

Una solución a esto podría ser que cada achievement tenga un nuevo parámetro de "creación" y una fecha de "solución" y así entre más pronto lo haya solucionado más "puntos" obtenga. La fórmula podría ser:

userData.points += achievement.points + ((10 * 60)/(achievement.solve_date - achievement.creation_date).

*Nota: la operación de las fechas sería con respecto a los segundos, y la expresión (10*60) es pensando en un límite de 10 minutos máximo

**Comment by danmt** [comment]
Que buen comentario!!!

El algoritmo se comporta exactamente como describes y me parece que tu solución es bastante interesante.

La solución que yo tenia pensado para este problema era tener "time bonus", mientras mas rapido respondas, mas "bono" tienes y ese bono viene sumado a los points que recibe este algoritmo. Así tenemos una manera un poco más justa.

Que opinas de hacer la suma de esos puntos extra antes de ejecutar el calculo del leaderboard?

Por otra parte, muchos deportes funcionan de esa manera, tu puedes ir ganando por mucha ventaja y al final alguien te repasa por milisegundos e igual te ganaron. Lo que hace esta modalidad valida para ciertos casos.

Asumiendo que tanto tu version como la mia son validas y que tienen casos de uso, veo que tenemos dos opciones:

- Poder escoger el algoritmo. (más versatil)
- Incluir el bono de tiempo antes de ejecutar el algoritmo. (menos codigo)

Cual te parece más viable?

**Comment by nihilia10** [comment]
Teniendo en cuenta que la selección de algoritmo implicaría cambios en el modelo y no es una necesdiad actualmente, me inclinaría por la solución del bono de tiempo! 🎉
